sudo: required
services:
  - docker

before_install:
  - docker build -t eliavhamburger/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true eliavhamburger/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "containerized-webapp"
  env: "Containerized-webapp-env"
  bucket_name: "elasticbeanstalk-us-east-1-553884453746"
  bucket_path: "containerized-webapp"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
